---
jobs:
  - name: hello
    public: true
    plan:
      - task: docker-python
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: python
              tag: slim-buster
          run:
            path: /bin/sh
            args:
            - -exc
            - |
              python -c 'print("This is my python code")'